package app.gui;

import java.security.InvalidAlgorithmParameterException;
import java.security.KeyPair;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

import javax.swing.JOptionPane;

import org.hyperledger.fabric.gateway.Contract;
import org.hyperledger.fabric.gateway.ContractException;

import app.user.ReadOnlyAppUser;
import app.utils.ByteUtils;
import app.utils.Cryptography;

public class ForumJFrame extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form ForumJFrame
     */
    private ForumJFrame(Contract contract) {
        this.contract = contract;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPublicKeyJTextField = new javax.swing.JTextField();
        userPrivateKeyJTextField = new javax.swing.JTextField();
        generateKeyPairJButton = new javax.swing.JButton();
        pointAmountJTextField = new javax.swing.JTextField();
        refreshPointAmountJButton = new javax.swing.JButton();
        pointAmountJLabel = new javax.swing.JLabel();
        MessageJTextField = new javax.swing.JTextField();
        searchJTextField = new javax.swing.JTextField();
        contentJTabbedPane = new javax.swing.JTabbedPane();
        viewPostJPanel = new javax.swing.JPanel();
        publishPostJPanel = new javax.swing.JPanel();
        postEditorJScrollPane = new javax.swing.JScrollPane();
        postEditorJTextArea = new javax.swing.JTextArea();
        publishPostSubmitJButton = new javax.swing.JButton();
        publishPostResetJButton = new javax.swing.JButton();
        userSearchJSeparator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userPublicKeyJTextField.setToolTipText("User Public Key");
        userPublicKeyJTextField.setActionCommand("<Not Set>");
        userPublicKeyJTextField.setName(""); // NOI18N

        userPrivateKeyJTextField.setToolTipText("User Private Key");
        userPrivateKeyJTextField.setName(""); // NOI18N

        generateKeyPairJButton.setText("Generate Key Pair");
        generateKeyPairJButton.setName(""); // NOI18N
        generateKeyPairJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateKeyPairJButtonActionPerformed(evt);
            }
        });

        pointAmountJTextField.setEditable(false);
        pointAmountJTextField.setToolTipText("Point Amount");
        pointAmountJTextField.setName(""); // NOI18N

        refreshPointAmountJButton.setText("Refresh");
        refreshPointAmountJButton.setName(""); // NOI18N
        refreshPointAmountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPointAmountJButtonActionPerformed(evt);
            }
        });

        pointAmountJLabel.setText("Point Amount");
        pointAmountJLabel.setToolTipText("");
        pointAmountJLabel.setName(""); // NOI18N

        MessageJTextField.setEditable(false);
        MessageJTextField.setToolTipText("Message");

        searchJTextField.setToolTipText("Search Bar");

        javax.swing.GroupLayout viewPostJPanelLayout = new javax.swing.GroupLayout(viewPostJPanel);
        viewPostJPanel.setLayout(viewPostJPanelLayout);
        viewPostJPanelLayout.setHorizontalGroup(
            viewPostJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1275, Short.MAX_VALUE)
        );
        viewPostJPanelLayout.setVerticalGroup(
            viewPostJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        contentJTabbedPane.addTab("Posts", viewPostJPanel);

        postEditorJTextArea.setColumns(20);
        postEditorJTextArea.setRows(5);
        postEditorJScrollPane.setViewportView(postEditorJTextArea);

        publishPostSubmitJButton.setText("Publish");
        publishPostSubmitJButton.setToolTipText("");

        publishPostResetJButton.setText("Reset");

        javax.swing.GroupLayout publishPostJPanelLayout = new javax.swing.GroupLayout(publishPostJPanel);
        publishPostJPanel.setLayout(publishPostJPanelLayout);
        publishPostJPanelLayout.setHorizontalGroup(
            publishPostJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(postEditorJScrollPane)
            .addGroup(publishPostJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(publishPostResetJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1115, Short.MAX_VALUE)
                .addComponent(publishPostSubmitJButton)
                .addContainerGap())
        );
        publishPostJPanelLayout.setVerticalGroup(
            publishPostJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publishPostJPanelLayout.createSequentialGroup()
                .addComponent(postEditorJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(publishPostJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publishPostSubmitJButton)
                    .addComponent(publishPostResetJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentJTabbedPane.addTab("Publish", publishPostJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchJTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userPublicKeyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPrivateKeyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateKeyPairJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pointAmountJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pointAmountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshPointAmountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(contentJTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(MessageJTextField, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(userSearchJSeparator)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPublicKeyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPrivateKeyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateKeyPairJButton)
                    .addComponent(refreshPointAmountJButton)
                    .addComponent(pointAmountJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pointAmountJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userSearchJSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(searchJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentJTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MessageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateKeyPairJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateKeyPairJButtonActionPerformed
        if(!this.userPrivateKeyJTextField.getText().isEmpty() || !this.userPublicKeyJTextField.getText().isEmpty()) {
            int choice = JOptionPane.showConfirmDialog(null, "Do you want to overwrite the existing Public and/or Private Keys?", "Warning", JOptionPane.OK_CANCEL_OPTION);
            if(choice == JOptionPane.CANCEL_OPTION) {
                return;
            }
        }
        try {
            KeyPair keyPair = Cryptography.generateRandomKeyPair();
            String publicKeyString =  ByteUtils.toHexString(keyPair.getPublic().getEncoded());
            String privateKeyString =  ByteUtils.toHexString(keyPair.getPrivate().getEncoded());
            this.userPublicKeyJTextField.setText(publicKeyString);
            this.userPrivateKeyJTextField.setText(privateKeyString);
            JOptionPane.showMessageDialog(null, "Please save the generated Public/Private Key Pair.");
        } catch (InvalidAlgorithmParameterException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_generateKeyPairJButtonActionPerformed

    private void refreshPointAmountJButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_refreshPointAmountJButtonActionPerformed
        String userPublicKey = this.userPublicKeyJTextField.getText();
        String pointAmount = new String();
        try {
            final var appUser = new ReadOnlyAppUser(this.contract,
                    Cryptography.parsePublicKey(ByteUtils.toByteArray(userPublicKey)));
            pointAmount = appUser.getPointAmount();
        } catch (ContractException e) {
            e.printStackTrace();
        } catch (InvalidKeySpecException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
        this.pointAmountJTextField.setText(pointAmount);
    }// GEN-LAST:event_refreshPointAmountJButtonActionPerformed

    public static void run(Contract contract) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForumJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForumJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForumJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForumJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForumJFrame(contract).setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        run(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MessageJTextField;
    private javax.swing.JTabbedPane contentJTabbedPane;
    private javax.swing.JButton generateKeyPairJButton;
    private javax.swing.JLabel pointAmountJLabel;
    private javax.swing.JTextField pointAmountJTextField;
    private javax.swing.JScrollPane postEditorJScrollPane;
    private javax.swing.JTextArea postEditorJTextArea;
    private javax.swing.JPanel publishPostJPanel;
    private javax.swing.JButton publishPostResetJButton;
    private javax.swing.JButton publishPostSubmitJButton;
    private javax.swing.JButton refreshPointAmountJButton;
    private javax.swing.JTextField searchJTextField;
    private javax.swing.JTextField userPrivateKeyJTextField;
    private javax.swing.JTextField userPublicKeyJTextField;
    private javax.swing.JSeparator userSearchJSeparator;
    private javax.swing.JPanel viewPostJPanel;
    // End of variables declaration//GEN-END:variables

    private Contract contract;
}
