# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: java_gradle_build

on:
  push:
    branches: [ main ]
    paths:
      - '**.java'
      - '**.gradle'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.java'
      - '**.gradle'
      - '.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Gradle Build blockchain
      working-directory: ./blockchain
      run: gradle build
    - name: Gradle Build application
      working-directory: ./application
      run: gradle build
